spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/windsurf?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: WindsurfHikariCP
      connection-test-query: SELECT 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

windsurf:
  database:
    # 是否开启SQL性能分析（开发环境建议开启）
    p6spy: false
    # 是否开启多数据源
    multiple-data-source: false
    # 是否开启分页插件
    enable-pagination: true
    # 是否开启乐观锁插件
    enable-optimistic-locker: true
    # 是否显示SQL（开发环境建议开启）
    show-sql: false
